import type { Metadata } from "next";
import localFont from "next/font/local";
import {
    Antonio,
    Inter,
    Ma_Shan_Zheng,
    ZCOOL_KuaiLe,
    ZCOOL_QingKe_HuangYou,
    Zhi_Mang_Xing,
} from "next/font/google";

import "./globals.css";
import LayoutWrapper from "@/components/LayoutWrapper";

const inter_init = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
});

const antonio = Antonio({
    subsets: ["latin"],
    display: "swap",
    weight: "700",
    variable: "--font-antonio",
});

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

const zcool = ZCOOL_QingKe_HuangYou({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-zcool-qingke-huangyou",
});

const maShanZheng = Ma_Shan_Zheng({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-maShanZheng",
});

const zcoolKuaiLe = ZCOOL_KuaiLe({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-zcool-kuai-le",
});

export const metadata: Metadata = {
    title: "Year of Snake 2025",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={` ${zcoolKuaiLe.variable} ${antonio.variable} ${maShanZheng.variable} ${zcool.variable} ${inter_init.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
                style={{
                    overscrollBehavior: "none",
                }}
            >
                <LayoutWrapper>{children}</LayoutWrapper>
            </body>
        </html>
    );
}
